version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: bookflowdb
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: bookflow
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bookflow_phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "1234"
      PMA_PORT: 3306
    ports:
      - "8081:80"
    restart: unless-stopped

volumes:
  db_data: